### ISSUE TITLE
fails to build distutils (non-setuptools) packages

### ISSUE THREAD

**Issue by bernieke** [astraw/stdeb#97] opened 2015-02-23 11:06 UTC
When trying to build pyzmq release 13.1.0 I see the following:

```
make[1]: Entering directory `/mnt/disk/tmp/pip/pyzmq-13.1.0/deb_dist/pyzmq-13.1.0'
python setup.py clean -a
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: option -a not recognized
make[1]: *** [override_dh_auto_clean] Error 1
make[1]: Leaving directory `/mnt/disk/tmp/pip/pyzmq-13.1.0/deb_dist/pyzmq-13.1.0'
make: *** [clean] Error 2
dpkg-buildpackage: error: fakeroot debian/rules clean gave error exit status 2
Traceback (most recent call last):
  File "setup.py", line 1011, in <module>
    setup(**setup_args)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python2.7/dist-packages/stdeb/command/sdist_dsc.py", line 140, in run
    remove_expanded_source_dir=self.remove_expanded_source_dir,
  File "/usr/local/lib/python2.7/dist-packages/stdeb/util.py", line 1421, in build_dsc
    dpkg_genchanges(cwd=fullpath_repackaged_dirname)
  File "/usr/local/lib/python2.7/dist-packages/stdeb/util.py", line 538, in dpkg_genchanges
    process_command(args,cwd=cwd)
  File "/usr/local/lib/python2.7/dist-packages/stdeb/util.py", line 183, in process_command
    check_call(args, cwd=cwd)
  File "/usr/local/lib/python2.7/dist-packages/stdeb/util.py", line 46, in check_call
    raise CalledProcessError(retcode)
stdeb.util.CalledProcessError: 2
```

The setup.py of the package uses distutils (it does expand the arguments with install_requires if it detects setuptools is installed, but still uses the setup function from distutils.core)

The distutils clean command does not accept any arguments.

**Comment by astraw** [comment] 2015-02-23 18:47
pyzmq 13.1.0 [creates its own clean command](https://github.com/zeromq/pyzmq/blob/v13.1.0/setup.py#L717-L755). Standard distutils clean command does indeed accept an `--all` or `-a` option. This is actually tested as part of the stdeb test suite.

If projects override standard distutils commands without being compatible with standard arguments, there's little stdeb can do.

I'm closing this for now, as it is not a bug with stdeb.

**Closed by astraw** 2015-02-23 18:47 UTC
